version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/web
    environment:
      FLASK_ENV: development
      PORT: 80
      WORKERS: 2
    env_file:
      - ./.env.dev
  postgres:
    image: "postgres:alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=coderman
      - POSTGRES_PASSWORD=codermanpassword123
      - POSTGRES_DB=fellowship-class-profile
    ports:
      - "5432:5432"

volumes:
  postgres_data:
