name: Deploy

on:
  push:
    branches:
      - master
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.2.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fellowship-class-profile"
          heroku_email: "chrisngyn99@gmail.com"
